### PR TITLE
South African public holidays

### PR DESCRIPTION
**Pull request by sarelvdwalt**

### CODE REVIEW

**Comment by heiglandreas** [comment]
Thank you very much for your contribution! 

Do you have a link to a kind of official resource where people can check where you got the information from? It wod be great if you could add that either here to the PR or (even better) as content if the git commit message.

Thank you!

**Comment by sarelvdwalt** [comment]
Hey @heiglandreas 

Thank you :) I have amended the latest commit with the appropriate source. For reference, here it is: https://www.gov.za/about-sa/public-holidays

Regards,
Sarel

**Comment by heiglandreas** [comment]
Thank you!

I merged this even though I've seen that the Public holidays Act defines that each time a holiday falls on a sunday the following Monday shall be a holiday. So instead of using the `date` tag, we probably should use the `datefollowup`-tag for at least those that might occur on different weekdays.

**Comment by heiglandreas** [comment]
Though Ive just seen that i need to make the FollowUp-IteratorItem more configurable as it currently would move a holyday that falls on a saturday onto the following specified day as well. Which is not correct for south africa....

So it looks like I will have to modify that a bit :-) Thanks for letting me know

**Comment by sarelvdwalt** [comment]
Ah ok yes I was wondering about that. Ok let me know when you have the tweak in for the `datefollowup`-tag, and I'll make a PR to fix the XML up.

Thank you for this library though, it's going to be super useful to us!

**Pull request merged**
